packages/server/src/utils.ts
Request in Fetch has a `text` method which should be respected even if the body was parsed previously.
Currently `.json()` returns an object but `.text()` an empty string - they should be coherent.
=> fix(server): normalized request should implement the `text` method

packages/server/CHANGELOG.md, packages/server/test/node.spec.ts, packages/server/test/request-listener.spec.ts, packages/server/test/tserver.ts
Use "tserver" that gets properly disposed and auto cleans up. Also avoid sharing servers for tests.
P.S. I get a **big** performance boost locally, the `request-listener.spec` ran for ~1min and now completes in ~4secs.
=> Stabilise and improve tests

.changeset/cuddly-bears-explode.md, packages/server/src/index.ts, packages/server/src/utils.ts
- Goodbye `any`s
- `ServerAdapterObject.fetch` now overloads expecting `TServerContext`
- Smaller cleanup
=> Improve types

.changeset/dry-cougars-check.md, packages/fetch/dist/create-node-ponyfill.js, packages/server/test/node.spec.ts
Closes https://github.com/dotansimha/graphql-yoga/issues/2255
=> fix: http2 support when using Node ponyfill

.changeset/unlucky-lobsters-try.md, packages/fetch/dist/create-node-ponyfill.js, packages/server/test/request-listener.spec.ts
Closes https://github.com/dotansimha/graphql-yoga/issues/2304
node-fetch ponyfilled requests dont have an abort signal associated. See related issue: https://github.com/node-fetch/node-fetch/issues/1439.
=> Node ponyfill requests must have an abort signal

.changeset/wicked-experts-attend.md, packages/server/src/createServerAdapter.ts, packages/server/test/adapter.fetch.spec.ts
As discussed in https://github.com/dotansimha/graphql-yoga/pull/2324, this PR fixes copying non-enumerable properties to the server context.
A test has been added that checks:
- if non-enumerable properties are copied
- if their non-enumerability is kept
=> Copy non-enumerable properties to server context

.changeset/soft-vans-invent.md, packages/events/dist/index.d.ts, packages/fetch/dist/index.d.ts
Sorry for going straight for a PR, I figured this fix was best described with code.
We're seeing issues with trying to use libraries that both declare global symbols such as `_fetch`, in this case this library along with `cross-fetch`. Due to these libraries both declaring this same global type, TypeScript will treat this as an error simply if both dependencies are installed in the same project. Using `--skipLibCheck` is not an option as this is an important check that we want to keep.
There are other solutions to this issue, but I figured the one I propose is the cleanest. `globalThis` has been available in TypeScript [since 3.4](https://devblogs.microsoft.com/typescript/announcing-typescript-3-4/#type-checking-for-globalthis), released 4 years ago.
Please describe the tests that you ran …
=> fix(events,fetch): avoid polluting global types

.changeset/calm-cars-accept.md, packages/cookie-store/src/CookieStore.ts, packages/cookie-store/src/getCookieString.ts, packages/cookie-store/src/types.ts, packages/cookie-store/test/getCookieString.spec.ts
Add the possibility to create HttpOnly cookies
[CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
style guidelines of this project
=> (feat:cookie-store) add httpOnly

.changeset/clean-schools-behave.md, packages/node-fetch/src/Body.ts, packages/node-fetch/tests/Body.spec.ts
Fixes https://github.com/ardatan/whatwg-node/issues/703
=> fix(node-fetch): resolve immediately if the body is empty

.changeset/lucky-moons-study.md, packages/server/src/uwebsockets.ts, packages/server/test/node.spec.ts
Fixes https://github.com/ardatan/whatwg-node/issues/783
=> fix(server): handle query params in uWS

.changeset/@whatwg-node_node-fetch-990-dependencies.md, .changeset/three-chefs-study.md, packages/node-fetch/package.json, packages/node-fetch/src/URL.ts, packages/node-fetch/src/declarations.d.ts, yarn.lock
Issue: https://github.com/petkaantonov/urlparser/issues/20
Fork: https://github.com/kamilkisiela/fast-url-parser
Fixes https://github.com/ardatan/whatwg-node/issues/968
=> Fix node:punycode usage by using a fork of fast-url-parser

.changeset/fresh-cameras-search.md, jest.config.js, package.json, packages/node-fetch/src/declarations.d.ts, packages/node-fetch/src/fetchCurl.ts, packages/node-fetch/tests/fetch.spec.ts, packages/server/test/test-fetch.ts
This PR is to help identify/address an issue we reported with the Guild team via Slack communications.
We are experiencing issues with aborts against `libcurl` powered requests where the responses are being streamed.
The above code, when hit, produces the following error:
```s
A libcurl function was given a bad argument
at Curl.pause (node_modules/node-libcurl/lib/Curl.ts:780:13)
at EventTarget.fetchRequest._signal.onabort (node_modules/@whatwg-node/node-fetch/cjs/fetchCurl.js:61:36)
```
I have tried to reproduce this via a test, but in doing this I think I have uncovered other potential issues with the tests configuration and the implementation of the `libcurl` wrapper.
The test runs successfully for the `node-fetch` implementation run, but fails for the `libcurl` implementation run. …
=> Adds test against fetch calls where an AbortSignal hits a streaming response

.changeset/long-suits-train.md, packages/node-fetch/src/Body.ts, packages/node-fetch/src/ReadableStream.ts, packages/server/package.json, packages/server/test/fastify.spec.ts, yarn.lock
No issue yet!
When using `createServerAdapter` in fastify to render React to readable streams, the adapter errors out with the following message:
```
Cannot create proxy with a non-object as target or handler
```
Related # (issue)
**Test Environment**:
- OS: MacOS
- `server`: main
- NodeJS: v20.10.0
[CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
style guidelines of this project
This is an initial test to kick off discussion, I'm not sure whether you will want react as a devDependency in your repo. If you're okay with this I will add the same tests to express.spec and node.spec (which will probably pass)
=> Support native `ReadableStream` as `BodyInit` & tests for React streaming response w/ Fastify

e2e/deno/e2e.ts, e2e/deno/tsconfig.json, packages/server/README.md
[`Deno.serve`](https://deno.land/api?s=Deno.serve) was stabilized in Deno [v1.35.0](https://github.com/denoland/deno/releases/tag/v1.35.0) back in 2023 July. This updates the documentation example to use the current API.
Ref: [stabilization announcement in the Deno blog](https://deno.com/blog/v1.35#denoserve-is-now-stable)
=> docs(server): update deno section

.changeset/real-bananas-visit.md, packages/server/src/plugins/useCors.ts, packages/server/test/useCors.spec.ts
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._
Reading the code, I stumbled on this code mistake where `Vary: Origin` would be overwritten by the `Vary: Access-Control-Request-Headers` because of a missing `else`.
Related # (issue)
expected)
Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate
Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration
**Test Environment**:
- OS:
- `package-name`:
- …
=> fix: Vary: Origin header overwritten

.changeset/lemon-coats-learn.md, .changeset/olive-tigers-sort.md, .github/workflows/pr.yml, packages/node-fetch/src/fetchNodeHttp.ts, packages/server/src/createServerAdapter.ts, packages/server/src/index.ts, packages/server/src/plugins/types.ts, packages/server/src/plugins/useContentEncoding.ts, packages/server/src/utils.ts, packages/server/test/compression.spec.ts
New plugin to handle E2E request compression
When the client provides `Accept-Encoding` header, if the server supports the encoding, it will compress the response body. This will reduce the size of the response body and improve the performance of the application. 
On the other hand, if the client sends `Content-Encoding` header, the server will decompress the request body before processing it. This will allow the server to handle the request body in its original form. 
If the server does not support the encoding, it will respond with `415 Unsupported Media Type` status code. 
`serverAdapter`'s `fetch` function handles the compression and decompression of the request and response bodies. 
```ts
import {createServerAdapter, useContentEncoding, Response} from '@whatwg-node/server';
const …
```
=> feat(server): handle compression/decompression bodies

.changeset/eighty-worms-accept.md, package.json, packages/node-fetch/src/Request.ts, packages/node-fetch/src/fetchCurl.ts, packages/node-fetch/src/fetchNodeHttp.ts, packages/node-fetch/tests/fetch.spec.ts, packages/server/test/test-fetch.ts
Use suggested \`pipeline\` from \`node:streams\` to pipe streams to the final Response object
=> enhance(node-fetch): use `pipeline` from `node:streams` to pipe streams

.changeset/ninety-pigs-bathe.md, .changeset/young-dancers-nail.md, packages/node-fetch/src/Request.ts, packages/node-fetch/src/fetch.ts, packages/node-fetch/src/fetchCurl.ts, packages/node-fetch/tests/http2.spec.ts, packages/server/test/test-fetch.ts
When cURL is used as the HTTP client implementation instead of node:http,
`SSL_VERIFYPEER` should be set `false` when the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable is set to `0`.
`CAINFO` should be set to the value of the `NODE_EXTRA_CA_CERTS` environment variable.
This allows the cURL client to use the same CA certificates and SSL configuration as `node:http`
=> enhance(node-fetch): respect Node SSL-related env vars

.changeset/plenty-walls-clap.md, packages/server/src/utils.ts, packages/server/src/uwebsockets.ts, packages/server/test/server-context.spec.ts, packages/server/test/utils.spec.ts
See https://github.com/ardatan/whatwg-node/pull/1796
=> Avoid polluting the original object in case of `Object.create`

.changeset/plenty-walls-clap.md, packages/server/src/types.ts, packages/server/src/utils.ts, packages/server/src/uwebsockets.ts, packages/server/test/fetch-event-listener.spec.ts, packages/server/test/server-context.spec.ts, packages/server/test/useErrorHandling.spec.ts, packages/server/test/utils.spec.ts
See https://github.com/ardatan/whatwg-node/pull/1796
=> Avoid polluting the original object in case of Object.create

.changeset/olive-mirrors-cover.md, packages/server/src/createServerAdapter.ts, packages/server/src/plugins/types.ts, packages/server/test/adapter.fetch.spec.ts
- New `onDispose` hook which is alias of `Symbol.asyncDispose` for Explicit Resource Management
- Registration of the server adapter's disposal to the global process termination listener is now opt-in and configurable.
```ts
const plugin: ServerAdapterPlugin = {
onDispose() {
console.log('Server adapter is disposed');
}
};
const serverAdapter = createServerAdapter(() => new Response('Hello world!'), {
plugins: [plugin],
// Register the server adapter's disposal to the global process termination listener
// Then the server adapter will be disposed when the process exit signals only in Node.js!
disposeOnProcessTerminate: true
});
await serverAdapter.dispose();
// Prints 'Server adapter is disposed'
```
=> `onDispose` and other disposal improvements

.changeset/blue-pugs-provide.md, packages/server/src/createServerAdapter.ts, packages/server/test/fastify.spec.ts
While calling `handleNodeRequest` or `handleNodeRequestAndResponse`, `waitUntil` is not added automatically as in `requestListener` for Node.js integration.
This change adds `waitUntil` into the `serverContext` if not present.
Fixes the issue with Fastify integration that uses the mentioned methods
=> fix(server): add `waitUntil` to the server context in Fastify integration

packages/server/README.md
Closes https://github.com/ardatan/whatwg-node/issues/1907
=> DOCS: Explicit Resource Management, cancellation and more

packages/cookie-store/src/CookieStore.ts, packages/cookie-store/src/types.ts, packages/disposablestack/src/AsyncDisposableStack.ts, packages/disposablestack/src/DisposableStack.ts, packages/node-fetch/src/Body.ts, packages/node-fetch/src/Request.ts, packages/node-fetch/src/Response.ts, packages/node-fetch/src/fetchNodeHttp.ts, packages/server/src/utils.ts, tsconfig.json
Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
Fixes https://github.com/ardatan/whatwg-node/issues/391
expected)
Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate
Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration
**Test Environment**:
- OS:
- `package-name`:
- NodeJS:
[CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
style guidelines of this project
If this is a relatively large …
=> set exactOptionalPropertyTypes: true, improved types

.changeset/seven-forks-tease.md, packages/node-fetch/src/fetchCurl.ts, packages/node-fetch/tests/fetch.spec.ts, packages/server/test/abort.spec.ts, yarn.lock
This PR adds two tests;
- Adds an `AbortSignal` from an `AbortController` never aborts, and the fetch call succeeds to see if it leaks
- Adds an `AbortSignal.timeout` and it doesn't timeout and fetch call succeeds before it times out. And we check if it leaks
And it also removes the event listener added in `node-libcurl` based fetch implementation to make sure it doesn't leak.
This change doesn't affect Hive Gateway's this issue https://github.com/graphql-hive/gateway/issues/303#issuecomment-2575383178 because Hive GW doesn't use node-libcurl directly. Only tests are added to see if the leak is reproduced regardless the change.
=> Test if it leaks when the given signal never aborts and connection succeeds

.changeset/afraid-lies-nail.md, packages/node-fetch/src/ReadableStream.ts
`ReadableStream`'s `Symbol.asyncIterator` now returns `AsyncIterableIterator` like before even if it
is ok to return `AsyncIterator`.
It is safer to return `AsyncIterableIterator` because it is a common mistake to use `AsyncIterator` as `AsyncIterable`.
=> enhance(node-fetch): make `ReadableStream[Symbol.asyncIterator]` `AsyncIterableIterator` rather than `AsyncIterator` only

.changeset/nine-moose-shake.md, packages/node-fetch/src/Headers.ts, packages/node-fetch/tests/Headers.spec.ts
Fixes https://github.com/ardatan/whatwg-node/issues/1781
=> fix(node-fetch): inspect null header values correctly

.changeset/@whatwg-node_server-2145-dependencies.md, packages/server/CHANGELOG.md, packages/server/package.json, packages/server/src/createServerAdapter.ts, packages/server/src/index.ts, packages/server/src/plugins/types.ts, packages/server/test/instrumentation.spec.ts, yarn.lock
Continue https://github.com/n1ru4l/envelop/pull/2486
=> Rename instruments to instrumentation

.changeset/old-flowers-care.md, packages/promise-helpers/src/index.ts, packages/promise-helpers/tests/handleMaybePromise.spec.ts
This is a simple change to remove VoidFunction which is not supposed to be a global. See: https://github.com/lukeed/uvu/issues/89#issuecomment-771248854
Related # (issue)
Fixes #2275
expected)
=> fix(types): remove VoidFunction

.changeset/whole-planes-mate.md, packages/node-fetch/src/FormData.ts, packages/node-fetch/src/TransformStream.ts, packages/node-fetch/src/WritableStream.ts, packages/node-fetch/src/fetchNodeHttp.ts, packages/node-fetch/src/utils.ts, packages/promise-helpers/src/index.ts, packages/promise-helpers/tests/handleMaybePromise.spec.ts, packages/server/package.json, packages/server/src/createServerAdapter.ts, packages/server/src/utils.ts, packages/server/test/reproductions.spec.ts, packages/server/test/test-server.ts, test.mjs, yarn.lock
Some implementations like `compression` npm package do not implement `response.write(data, callback)` signature, but whatwg-node/server waits for it to finish the response stream.
Then it causes the response stream hangs when the compression package takes the stream over when the response data is larger than its threshold.
It is actually a bug in `compression` package;
[expressjs/compression#46](https://github.com/expressjs/compression/issues/46)
But since it is a common mistake, we prefer to workaround this on our end.
Now after calling `response.write`, it no longer uses callback but first it checks the result;
if it is `true`, it means stream is drained and we can call `response.end` immediately.
else if it is `false`, it means the stream is not drained yet, so we can wait for the …
=> fix(server): do not wait for `response.write` for `response.end`

.changeset/cruel-colts-show.md, packages/promise-helpers/src/index.ts
Instead of asking the global namespace for it every time, store the reference and put access it faster each time it's used.
Comparing to the published server v0.10.5 with #2383 reverted. I reverted it because even though removing of the `WeakMap` improves performance, the other changes make it dunk. When I picked changes from #1505 (and ended with the same approach as #2383 without removing public API), it was 3-5% faster. 
Fastify benchmarks against `node:http`.
```
┌──────────────────────────┬─────────┬────────┬────────────┬──────────────┬───────────────┐
│                          │ Version │ Router │ Requests/s │ Latency (ms) │ Throughput/Mb │
├──────────────────────────┼─────────┼────────┼────────────┼──────────────┼───────────────┤
│ node-http                │ v24.0.1 │ ✗      │ …
```
=> refactor(promise-helpers): reuse promise Symbol

.changeset/curvy-seas-smoke.md, eslint.config.mjs, package.json, packages/node-fetch/src/Body.ts, packages/node-fetch/src/Headers.ts, packages/node-fetch/src/Request.ts, packages/node-fetch/src/Response.ts, packages/node-fetch/src/fetchCurl.ts, packages/node-fetch/src/fetchNodeHttp.ts, packages/node-fetch/src/utils.ts, packages/server/src/createServerAdapter.ts, packages/server/src/plugins/useCors.ts, packages/server/src/utils.ts, packages/server/test/reproductions.spec.ts, packages/server/test/server.bench.ts, tsconfig.build.json, tsconfig.json, vitest.config.ts, vitest.projects.ts, yarn.lock
- Avoid creating `AbortController` and `AbortSignal` if not needed with `new Request` because it is expensive
- Avoid creating a map for `Headers` and try to re-use the init object for `Headers` for performance with a single-line `writeHead`.
- Avoid creating `Buffer` for `string` bodies for performance
- Use `setHeaders` which accepts `Headers` since Node 18 if needed to forward `Headers` to Node
=> Performance optimizations
